// flow-typed signature: b6bb10a6e49144710ff51b1a4abc7c80
// flow-typed version: <<STUB>>/react-bootstrap4-modal_v^1.6.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap4-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap4-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap4-modal/dist/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap4-modal/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap4-modal/dist/index.js' {
  declare module.exports: $Exports<'react-bootstrap4-modal/dist/index'>;
}
declare module 'react-bootstrap4-modal/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap4-modal/lib/index'>;
}
